// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLIzGQCgY1iSesTwtV9vByav5uy6aGTs',
    appId: '1:482915531162:web:aac9820df085276ecae223',
    messagingSenderId: '482915531162',
    projectId: 'smart-ev-learning-companion',
    authDomain: 'smart-ev-learning-companion.firebaseapp.com',
    storageBucket: 'smart-ev-learning-companion.firebasestorage.app',
    measurementId: 'G-SQEXSFFPSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-YebH2Y5DFxj2MO78fKNhWs_TUoz7mI',
    appId: '1:482915531162:android:161d1e08862e82c9cae223',
    messagingSenderId: '482915531162',
    projectId: 'smart-ev-learning-companion',
    storageBucket: 'smart-ev-learning-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4U843PYX1m77SDlqWIjfKWoxQcC2-3xo',
    appId: '1:482915531162:ios:186bcb7143d7af47cae223',
    messagingSenderId: '482915531162',
    projectId: 'smart-ev-learning-companion',
    storageBucket: 'smart-ev-learning-companion.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4U843PYX1m77SDlqWIjfKWoxQcC2-3xo',
    appId: '1:482915531162:ios:186bcb7143d7af47cae223',
    messagingSenderId: '482915531162',
    projectId: 'smart-ev-learning-companion',
    storageBucket: 'smart-ev-learning-companion.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQLIzGQCgY1iSesTwtV9vByav5uy6aGTs',
    appId: '1:482915531162:web:d9be58ca9e209081cae223',
    messagingSenderId: '482915531162',
    projectId: 'smart-ev-learning-companion',
    authDomain: 'smart-ev-learning-companion.firebaseapp.com',
    storageBucket: 'smart-ev-learning-companion.firebasestorage.app',
    measurementId: 'G-28NS7BKM6R',
  );
}
